= Job Configuration

The jobs to be executed are configured in the `application.yml` file.

[IMPORTANT]
====
Basic configurations are set at the `microprofile-config.yml` level in the `ticker-core-quartz` dependency, so this file should not be overridden in the implementing project.
====

.application.yml - Defining Quarkus REST clients
[source,yml]
----
quarkus:
    rest-client:
        ITickerTestRestRegisteredClient: <1>
            url: http://localhost:8080 <2>
            scope: jakarta.enterprise.context.ApplicationScoped <3>
            read-timeout: 5000 <4>
            connect-timeout: 5000 <5>
----

NOTE: It is a general solution in Quarkus that the definitions of REST clients to be used in the application can be specified in this way.

The example contains the most basic configurations:

<1> Under the quarkus.rest-client config, the identifier of the REST client interface must be given, which is the interface with its package, or if the configKey is provided in the `@RegisterRestClient` annotation, then it should be referenced here based on that.
<2> This is the place to specify the baseUri.
<3> Determination of the scope of the injected RestClient interface. It's recommended to use ApplicationScoped, as it can avoid many issues (rest client closure, memory leaks, etc.); be careful not to try to destroy the bean if multiple jobs use the interface, as it will lead to errors. Increasing the thread pool is recommended if many jobs need to run on the same REST client.
<4> The response waiting timeout can be defined.
<5> The connection timeout can be defined.

For increasing the thread pool mentioned in point 3, the `DefaultRestClientBuilderListener` class should be inherited and the `onNewBuilder` method overridden, where the thread pool and the max-pooled-per-route parameters can be adjusted:

[source,java]
----
    @Override
    public void onNewBuilder(RestClientBuilder builder) {
        super.onNewBuilder(builder);
        builder.property("resteasy.connectionPoolSize",75);
        builder.property("resteasy.maxPooledPerRoute",50);
----

For further options, see: https://download.eclipse.org/microprofile/microprofile-rest-client-3.0/microprofile-rest-client-spec-3.0.html

.application.yml - Defining the list of Jobs
[source,yml]
----
ticker:
    timer:
        activeJobs:
            - TEST_REST
            - TEST_REST_2
            - ..
----

== Using Microprofile Rest-based Job

The job allows HTTP calls to be initiated with the help of an MP REST client.

The following example demonstrates its use:

.application.yml
[source,yaml]
----
ticker:
    timer:
        activeJobs:
            - TEST_REST <1>
        job:
            TEST_REST: <2>
                code: REST_QUARTZ_TEST <3>
                cron: "*/10 * * ? * *" <4>
                actionClass: hu.icellmobilsoft.ticker.quartz.service.timer.job.mprestclient.MicroprofileRestClientJob <5>
                config:
                    mpRestClientClass: hu.icellmobilsoft.ticker.sample.service.rest.test.api.ITickerTestRestRegisteredClient <6>
                    method: getTest(java.lang.String,java.lang.Integer,java.lang.Long,java.lang.Boolean,java.time.OffsetDateTime) <7>
                    parameters: <8>
                        - config
                        - 50
                        - 30
                        - true
                        - 2023-06-07T13:45:27.893013372Z
----

<1> - under ticker.timer.activeJobs, you can define which job should be active
<2> - under ticker.time.job, the jobs referenced in the first point can be defined
<3> - Using the code, you can search for the given job in the logs. It's found in Health as <code>-Job, and in logs like: `<<< End quartz job type [REST_QUARTZ_TEST job]`.
<4> - Cron settings
<5> - Action class that defines the job's process.
<6> - The action configuration where the mpRestClientClass can be specified, which is the REST client interface.
<7> - The action configuration where the method can be specified within the REST client interface.
<8> - The action configuration where the parameters for the method call can be specified. Any list element can be defined with a static method call using { at the beginning and } at the end.

== Using HTTP Call-based Job [[http_client_job]]

The job allows for the definition of basic HTTP calls.
The only task to be solved is if a custom body setup is needed, for example for a POST call, which can be solved with the method definition so far.

The following example demonstrates its use:

.application.yml
[source,yaml]
----
ticker:
    timer:
        activeJobs:
            - TEST_APACHE_HTTP_CLIENT <1>
        job:
            TEST_APACHE_HTTP_CLIENT: <2>
                code: TEST_APACHE_HTTP_CLIENT <3>
                cron: "*/1 * * ? * *" <4>
                actionClass: hu.icellmobilsoft.ticker.quartz.service.timer.job.httpclient.HttpClientJob <5>
            config:
                baseUrl: http://localhost:8080/test/ticker <6>
                method: Get <7>
                body: "&{hu.icellmobilsoft.ticker.common.util.version.BaseRequestUtil.generate}" # static method call <8>
                headers:
                    Content-Type: "application/xml"
                    Accept: "application/json"
                queryParams:
                    testString: value
                    testInteger: 1000
                    testLong: 50000
                    testBoolean: true
                    testOffsetDateTime: 2023-06-07T13:45:27.893013372Z
----

<1> - under ticker.timer.activeJobs, you can define which job should be active
<2> - under ticker.time.job, the jobs referenced in the first point can be defined
<3> - Using the code, you can search for the given job in the logs. It's found in Health as <code>-Job, and in logs like: `<<< End quartz job type [TEST_APACHE_HTTP_CLIENT job]`.
<4> - Cron settings
<5> - Action class that defines the job's process, in this example, one can use the HTTP Call-based job.
<6> - The action configuration where the baseUrl can be specified for the HTTP call
<7> - The action configuration where the method can be specified for the HTTP call
<8> - The action configuration where the body can be specified for the HTTP call. A static method call can also be defined in the body using &{ at the beginning and } at the end.
<9> - The action configuration where the headers can be specified for the HTTP call
<10> - The action configuration where the queryParams can be specified for the HTTP call
