:source-highlighter: rouge
:rouge-style: thankful_eyes
:icons: font
:table-stripes: even

= Ticker Module

== General

image:https://img.shields.io/github/actions/workflow/status/i-Cell-Mobilsoft-Open-Source/ticker-backend/compile_maven.yml?branch=main&logo=GitHub&style=plastic[Compile status,link=https://github.com/i-Cell-Mobilsoft-Open-Source/ticker-backend/actions/workflows/compile_maven.yml?query=branch%3Amain]
image:https://img.shields.io/maven-central/v/hu.icellmobilsoft.ticker/ticker?logo=apache-maven&style=for-the-badge)[Maven central version of Parent pom project]
image:https://img.shields.io/github/license/i-Cell-Mobilsoft-Open-Source/ticker-backend?style=plastic&logo=apache[License of Parent pom project]
image:https://img.shields.io/badge/Use_JakartaEE_10+-project-brightgreen.svg?style=plastic&logo=jakartaee[Use JakartaEE project]
image:https://img.shields.io/github/commit-activity/m/i-Cell-Mobilsoft-Open-Source/ticker-backend.svg?label=Commits&style=plastic&logo=git&logoColor=white[Commits]
image:https://img.shields.io/badge/JVM-17-brightgreen.svg?style=plastic&logo=openjdk[Supported JVMs]
image:https://img.shields.io/github/stars/i-Cell-Mobilsoft-Open-Source/ticker-backend?style=plastic[GitHub Repo Stars,link=https://github.com/i-Cell-Mobilsoft-Open-Source/ticker-backend/stargazers]

The goal of this project is to provide a modular solution for triggering processes via cron scheduling by calling specific API endpoints.

[NOTE]
====
Documentation: `https://i-cell-mobilsoft-open-source.github.io/ticker-backend/`
====

== Development

During development, using a mock service is recommended if the goal is to develop REST calls. To do this, start the mock-service from the available docker-compose configurations. Additionally, when running `maven clean install`, the application should be built using the `add-mockapi` profile to include the MicroProfile REST client API.

== Testing

There are two ways to perform testing.

A sub-project under `ticker-testsuite` is created, which is as independent as possible from the main project. It does not depend on the project itself but only utilizes the API part.

.Developer tests - ticker-testsuite
`<PROJECT_PATH>/ticker-testsuite`

The developer tests use the https://github.com/i-Cell-Mobilsoft-Open-Source/roaster[Roaster] project.
This is a completely standalone REST testing tool that performs external calls on the deployed application.
It can be executed directly through the developer UI (JUnit plugin) or via Maven (activating the "profile" switch), for example:

[source,bash]
----
cd local_path/ticker/ticker-testsuite/ticker-testsuite-sample/ticker-testsuite-sample-service
mvn verify -Dprofile <1>
mvn verify -Dprofile=sandbox,local <2>
----
<1> default parameters
<2> selected profiles from configuration files

== Release
The release process is automated and is executed using GitHub Actions.
For this, docker-compose and a Docker image are available.

./ticker/etc/release/Dockerfile
The release process consists of three main steps:

. Base image, which in this case is a Java 17 image
. Downloading the JAR file - retrieving the desired deployment file from Nexus
. Finalizing the Docker image - copying the JAR files, etc.

./ticker-backend/etc/release/docker-compose.yml
This file sets up the service variables and manages them together.

.Execution
Execution is done manually via https://github.com/i-Cell-Mobilsoft-Open-Source/ticker-backend/actions[GitHub Actions].
