:sectnums:
:sectnumlevels: 3

= Additional Information

== Useful Commands and Accesses
Commands used for development purposes,
which are used for setting up and starting developer environments.

The application can be started in several ways:

* Starting Quarkus dev with Maven
* Creating a Quarkus uber-jar and running this jar file using `java -jar`
** The same jar placed into a java docker image and run (using Dockerfile.uber-jar.jvm)

Docker-compose is used for creating and running Docker images.

[NOTE]
====
The project contains a sampler service that demonstrates the use of the module. This example is capable of running entirely on a local development machine. 
So there are no external dependencies.
====

=== Starting ticker-core-quartz-service Server in Different Ways

.IDE included Quarkus run config
----
Several IDEs offer native support for Quarkus, as they do for Spring Boot projects, recognizing and creating their own run configuration.
----

.Maven quarkus:dev
----
mvn clean compile quarkus:dev
----

IMPORTANT: The project consists of more than one module, as expected by Quarkus, therefore compile is necessary.

NOTE: With the help of the Quarkus Maven plugin, the project can be started in dev mode, activating several dev tools. More information: https://quarkus.io/guides/dev-mode-differences.

.Running Quarkus uber-jar in Docker
----
mvn clean install <1>
docker-compose -f <PROJECT_PATH>/ticker-backend/etc/docker-compose/docker-compose.local.ticker-service.yml up --build --force-recreate <2>
----

<1> is necessary for generating the jar that will be included in the Docker image.
<2> The docker compose command, issued in the project's root, initiates the docker-compose build (forcing a rebuild of the image if needed with the force recreate parameter), and starts up.

NOTE: Quarkus processes and optimizes beans at *build-time*, unlike traditional runtime dependency injection models. Thanks to this: Only the actually used classes are included in the final application, while unnecessary ones are automatically removed.

NOTE: MP Rest Client can only be configured at *build-time*, they cannot be dynamically registered or injected at runtime, therefore at build-time it can be packaged with a `Ticker core` module.

[[validating-with-test]]
== Validating job configuration existence with test

We provide an abstract test class which can be extended on project side to validate that all expected jobs have been configured.

.Test scoped dependency
[source,xml]
----
<dependency>
    <groupId>hu.icellmobilsoft.ticker</groupId>
    <artifactId>ticker-core-quartz</artifactId>
    <version>${version}</version>
    <classifier>tests</classifier>
    <scope>test</scope>
</dependency>
----

.Using of AbstractQuarkusTest class
[source,java]
----
@QuarkusTest <1>
public class ProjectQuarkusTestIT extends AbstractQuarkusTest { <2>

    @Override
    public List<String> getExpectedJobKeys() { <3>
        return List.of("...", "...");
    }
}
----
<1> add the QuarkusTest annotation
<2> extend AbstractQuarkusTest class
<3> override the getExpectedJobKeys method to return with the key list

* The expected job keys are the `ticker.timer.job.[jobName].code` configurations.
* The expected jobs should be active as well, thus listed in `ticker.timer.activeJobs` configuration.

