version: "3.8"

# run from project directory
# docker-compose -f ./etc/docker-compose/docker-compose.local.observability.yml up --build --force-recreate
services:
  prometheus:
    container_name: prometheus
    volumes:
      - '../config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml'
    image: ${OSS_DOCKER_REPOSITORY}/prom/prometheus:v2.40.2
    ports:
      - '9090:9090'
    deploy:
      resources:
        limits:
          #cpus: '0.01'
          memory: 128M
  grafana:
    container_name: grafana
    volumes:
      - '../config/grafana/provisioning/:/etc/grafana/provisioning/'
    image: ${OSS_DOCKER_REPOSITORY}/grafana/grafana:9.2.6
    ports:
      - '3000:3000'
    deploy:
      resources:
        limits:
          #cpus: '0.01'
          memory: 128M
  jaeger:
    container_name: jaeger
    image: ${OSS_DOCKER_REPOSITORY}/jaegertracing/all-in-one
    volumes:
      - '../config/jaeger/sampling_strategies.json:/etc/jaeger/sampling_strategies.json'
    ports:
      - '6831:6831/udp'
      - '16686:16686'
      - '14268:14268'
      - '5778:5778'

    deploy:
      resources:
        limits:
          #cpus: '0.01'
          memory: 128M
networks:
  default:
    external: true
    # if it could not be found on compose up, then execute: docker network create ticker-local-network
    name: ticker-local-network
