#-------------------------------
# Coffee config
#-------------------------------
coffee:
  app:
    projectStage: dev

#-------------------------------
# Quarkus settings
#-------------------------------
quarkus:
  arc:
    #    remove-unused-beans: false
    unremovable-types:
      # producer: https://github.com/quarkusio/quarkus/blob/3.15.3/extensions/quartz/runtime/src/main/java/io/quarkus/quartz/runtime/QuartzSchedulerImpl.java#L339
      - org.quartz.Scheduler
      # producer: hu.icellmobilsoft.ticker.quartz.service.timer.config.TimerConfigImpl
      - hu.icellmobilsoft.ticker.quartz.service.timer.config.ITimerConfig
      # @Named annotacio utan elvileg torolheto
      - hu.icellmobilsoft.coffee.module.mp.restclient.provider.DefaultLoggerClientRequestFilter
      - hu.icellmobilsoft.coffee.module.mp.restclient.provider.DefaultLoggerClientResponseFilter
      - hu.icellmobilsoft.coffee.tool.utils.stream.LoggingPublisher
      - hu.icellmobilsoft.coffee.module.mp.restclient.provider.DefaultSettingClientRequestFilter
      - hu.icellmobilsoft.coffee.rest.validation.xml.utils.XsdHelper
      - hu.icellmobilsoft.coffee.rest.validation.xml.error.XsdValidationErrorCollector
      - hu.icellmobilsoft.coffee.rest.validation.catalog.PublicCatalogResolver
      - hu.icellmobilsoft.ticker.samples.mockapi.MPTestRest

  # REST Client configuration
  # url: All requests performed per interface will use this configuration value as the base URL
  # scope: The default scope per interface.
  #   Supported scope values are @Singleton, @Dependent, @ApplicationScoped and @RequestScoped.
  #   The default scope is @Dependent.
  #   The default scope can also be defined on the interface
  # read / connection-timeout: default 30 seconds can be overridden in milliseconds
  rest-client:
    mockapi:
      url: http://localhost:1080
      scope: jakarta.enterprise.context.ApplicationScoped
      #read-timeout: 5000
      #connect-timeout: 5000
  swagger-ui:
    enable: true

ticker:
  timer:
    activeJobs:
      - TEST_REST
      - TEST_REST_2
      - TEST_APACHE_HTTP_CLIENT_GET
      - TEST_APACHE_HTTP_CLIENT_POST
    job:
      TEST_REST:
        code: TEST_REST
        cron: "*/2 * * ? * *"
        actionClass: hu.icellmobilsoft.ticker.quartz.service.timer.job.mprestclient.MicroprofileRestClientJob
        config:
          mpRestClientClass: hu.icellmobilsoft.ticker.samples.mockapi.MPTestRest
          method: getTest(java.lang.String,java.lang.Integer,java.lang.Long,java.lang.Boolean,java.time.OffsetDateTime)
          parameters:
            - config
            - 50
            - 30
            - true
            - 2023-06-07T13:45:27.893013372Z
      TEST_REST_2:
        code: TEST_REST_2
        cron: "*/2 * * ? * *"
        actionClass: hu.icellmobilsoft.ticker.quartz.service.timer.job.mprestclient.MicroprofileRestClientJob
        config:
          mpRestClientClass: hu.icellmobilsoft.ticker.samples.mockapi.MPTestRest
          method: postTest(hu.icellmobilsoft.coffee.dto.common.commonservice.BaseRequest,java.lang.String,java.lang.Integer,java.lang.Long,java.lang.Boolean,java.time.OffsetDateTime)
          parameters: [ "{hu.icellmobilsoft.ticker.core.quartz.service.version.BaseRequestUtil.generate}", "null", "null", "null", "null", "null" ]
      TEST_APACHE_HTTP_CLIENT_GET:
        code: TEST_APACHE_HTTP_CLIENT_GET
        cron: "*/2 * * ? * *"
        actionClass: hu.icellmobilsoft.ticker.quartz.service.timer.job.httpclient.HttpClientJob
        config:
          baseUrl: http://localhost:1080/test
          method: Get
          headers:
            Content-Type: "application/xml"
            Accept: "application/json"
          queryParams:
            testString: value
            testInteger: 1000
            testLong: 50000
            testBoolean: true
            testOffsetDateTime: 2023-06-07T13:45:27.893013372Z
      TEST_APACHE_HTTP_CLIENT_POST:
        code: TEST_APACHE_HTTP_CLIENT_POST
        cron: "*/2 * * ? * *"
        actionClass: hu.icellmobilsoft.ticker.quartz.service.timer.job.httpclient.HttpClientJob
        config:
          baseUrl: http://localhost:1080/test
          method: POST
          body: "&{hu.icellmobilsoft.ticker.core.quartz.service.version.BaseRequestUtil.generate}" # static method call
          headers:
            Content-Type: "application/xml"
            Accept: "application/xml"
          queryParams:
            testString: value
            testInteger: 1000
            testLong: 50000
            testBoolean: true
            testOffsetDateTime: 2023-06-07T13:45:27.893Z
