# build inditas
# docker compose -f ticker-backend/etc/release/docker-compose.yml build --no-cache
# image belemaszas
# docker run --rm -it icellmobilsoft/ticker-core-quartz-service:1.5.0 /bin/sh
# image inditasa
# docker run --rm -p 8080:8080 -p 9990:9990 icellmobilsoft/ticker-core-quartz-service:1.5.0

services:
  ticker-core-quartz-service-release:
    build:
      context: ../../
      dockerfile: etc/release/fast-jar.Dockerfile
      args:
        ICELL_JAVA_JRE_BASE_IMAGE: 'icellmobilsoft/base-java21jre:${OSS_BASEIMAGE_VERSION}'
        SERVICE: 'ticker-core-quartz-service'
        POM_GROUP_ID: 'hu.icellmobilsoft.ticker'
        POM_ARTIFACT_ID: 'ticker-core-quartz-service'
        POM_VERSION: '$RELEASED_VERSION'
        POM_EXTENSION: 'tar.gz'
    image: "$DOCKER_SERVICE_TICKER_CORE_QUARTZ_SERVICE:$RELEASED_VERSION"
