version: "3.8"

# build inditas
# docker-compose -f ticker-backend/etc/release/docker-compose.yml build --no-cache
# image belemaszas
# docker run --rm -it dockerhub.icellmobilsoft.hu/modules/ticker/ticker-core-quartz-service:0.1.0-SNAPSHOT /bin/sh
# image inditasa
# docker run --rm -p 8080:8080 -p 9990:9990 dockerhub.icellmobilsoft.hu/modules/ticker/ticker-core-quartz-service:0.1.0-SNAPSHOT

services:
  ticker-core-quartz-service-release:
    build:
      context: ../../
      dockerfile: etc/release/Dockerfile
      args:
        ICELL_JAVA_17_JRE_BASE_IMAGE: '${OSS_DOCKER_REPOSITORY}/icellmobilsoft/base-java17jre:${OSS_BASEIMAGE_VERSION}'
        POM_GROUP_ID: 'hu.icellmobilsoft.ticker'
        POM_ARTIFACT_ID: 'ticker-core-quartz-service'
        # RELEASED_VERSION erteket ci scriptek betoltik az inditott folyamat szerint
        POM_VERSION: '$RELEASED_VERSION'
        POM_EXTENSION: 'jar'
    image: "$DOCKER_SERVICE_TICKER_CORE_QUARTZ_SERVICE:$RELEASED_VERSION"
