:sectnums:
:sectnumlevels: 3

= Backend

The Ticker project can be divided into two parts. One is a sampler and its associated testsuite subproject, and the other part is the ticker-core-quartz module.

== Service

The sampler demonstrates how to use the module to create a service where you only need to link the *apit* at the dependency level with the *ticker-core-quartz module*.

The first step is to include the ticker-core-quartz module in the dependencies.

[source,xml]
----
<dependency>
    <groupId>hu.icellmobilsoft.ticker</groupId>
    <artifactId>ticker-core-quartz</artifactId>
</dependency>
----

Secondly, use the API dependency containing the interfaces that the module will call:

.Example API dependency
[source,xml]
----
<dependency>
    <groupId>hu.icellmobilsoft.sampler.api</groupId>
    <artifactId>api</artifactId>
</dependency>
----

IMPORTANT: It is important that since this is a Quarkus-based module, the implementing module must also use an application with the same version of Quarkus.

After that, when the application starts, the event defined in the `SchedulerController` will be triggered.

At this point, the `SchedulerController` will see the indexed interfaces and will start them according to the provided yml config.


include::sampler/index.adoc[leveloffset=+1]
