= Ticker core quartz service configuration

The Ticker Service must be accessible in the environments of the project(s) that intend to use it.
To achieve this, each instance of the service - along with its infrastructural requirements - must be deployed and configured for each (development/test/production) environment.

== Service Configuration

.Application
[source,properties]
----
COFFEE_APP_NAME=${quarkus.application.name}
COFFEE_CONFIG_XML_CATALOG_PATH=xsd/hu/icellmobilsoft/cfg/dto/super.catalog.xml
COFFEE_CONFIG_RESOURCE_BUNDLES= i18n.common-messages,i18n.messages
CONSOLE_LOGGING_ENABLED=true
----

=== Kubernetes deployment

* Recommended configuration

[options="header",cols="1,1,1"]
|===
|Parameter |Value |Description
|TICKER_LOG_CONSOLE_ENABLE| true | disable logging to console, default: true
|TICKER_LOG_FILE_ENABLE| false | disable logging to file, default: false
|TICKER_LOGSTASH_K8S_NAMESPACE | ticker-core-quartz-service | set K8S_NAMESPACE, default unknown
|CFG_LOGSTASH_MODULE_VERSION | | set moduleVersion key, default unknown
|TICKER_JAEGER_AGENT_HOST_PORT | jaeger:6831 | jaeger agent host, default localhost
|TICKER_JAEGER_SERVICE_NAME | ticker-core-quartz-service | Service name visible on the Jaeger interface (default ROOT.war)
|===

include::../quarkus/index.adoc[leveloffset=+1]

=== Observability

==== Metrics

The `hu.icellmobilsoft.ticker.quartz.service.quartz.util.QuartzJobUtil` class provides metrics about Quartz Jobs. We add our own `hu.icellmobilsoft.ticker.quartz.service.quartz.health.metric.MetricJobListener`, which implements `org.quartz.JobListener`, to the `org.quartz.Scheduler` via the `org.quartz.ListenerManager` interface.

Currently, the following Quartz Job metrics are available:

* Quartz job prev fire time
** The time of the previous Job execution
** key: `quartz_job_prev_fire_time`
* Quartz job next fire time
** The time of the next Job execution
** key: `quartz_job_next_fire_time`
* Quartz job run time
** The duration of the most recent Job execution
** key: `quartz_job_run_time`

The application server provides metrics at the `<host:port>/q/metrics` endpoint with the `application_` prefix.

.example
----
application_quartz_job_prev_fire_time{configKey="REST_QUARTZ_TEST-Job",quantile="0.5"} 1.66921282E12
application_quartz_job_next_fire_time{configKey="REST_QUARTZ_TEST-Job",quantile="0.5"} 1.66921283E12
application_quartz_job_run_time{configKey="REST_QUARTZ_TEST-Job",quantile="0.5"} 41.0

----

==== Health - startup/liveness/readiness

The service supports the use of k8s probes.

* started
http://localhost:9000/q/health/started
* live
http://localhost:9000/q/health/live
* ready
http://localhost:9000/q/health/ready
