= Ticker core quartz service konfiguráció

A Ticker Service szolgáltatást felhasználni kívánó projekt(ek) környezeteiben elérhető kell legyen.
Ehhez a service egy-egy példánya - infrastrukturális szükségleteivel együtt - minden egyes (fejlesztői/teszt/éles) környezetre telepítendő és konfigurálandó.

== Service Konfiguráció

.Alkalmazás
[source,properties]
----
COFFEE_APP_NAME=${quarkus.application.name}
COFFEE_CONFIG_XML_CATALOG_PATH=xsd/hu/icellmobilsoft/cfg/dto/super.catalog.xml
COFFEE_CONFIG_RESOURCE_BUNDLES= i18n.common-messages,i18n.messages
CONSOLE_LOGGING_ENABLED=true
----

=== Kubernetes deployment

* Ajánlott konfiguráció

[options="header",cols="1,1,1"]
|===
|Parameter |Value |Description
|TICKER_LOG_CONSOLE_ENABLE| true | konzolra logolás tiltása, default : true
|TICKER_LOG_FILE_ENABLE| false | fájlba logolás tiltása, default: false
|TICKER_LOGSTASH_K8S_NAMESPACE | ticker-core-quartz-service | K8S_NAMESPACE beállítása, default unknown
|CFG_LOGSTASH_MODULE_VERSION | | moduleVersion kulcs beállítása, default unknown
|TICKER_JAEGER_AGENT_HOST_PORT | jaeger:6831 | jaeger agent host, default localhost
|TICKER_JAEGER_SERVICE_NAME | ticker-core-quartz-service | Service name ami a Jaeger felületén is látható (alapértelmezetten ROOT.war)
|===

include::../quarkus/index.adoc[leveloffset=+1]

=== Observability

==== Metrikák

A `hu.icellmobilsoft.ticker.quartz.service.quartz.util.QuartzJobUtil` osztály szolgáltatja a Quartz Job-okról a metrikákat. Az `org.quartz.Scheduler`-be az `org.quartz.ListenerManager` interface-en keresztül adjuk hozzá a saját `hu.icellmobilsoft.ticker.quartz.service.quartz.health.metric.MetricJobListener`-ünket ami az `org.quartz.JobListener`-t implementálja.

Jelenleg az következő Quartz Job metrikák érhetőek el:

* Quartz job prev fire time
** Az előző Job futás időpontja
** kulcs: `quartz_job_prev_fire_time`
* Quartz job next fire time
** A következő Job futás időpontja
** kulcs: `quartz_job_next_fire_time`
* Quartz job run time
** A legutóbbi Job futás ideje
** kulcs: `quartz_job_run_time`

A metrikákat az alkalmazásszerver a `<host:port>/q/metrics` végponton szolgáltatja `application_` prefix-szel ellátva.

.példa
----
application_quartz_job_prev_fire_time{configKey="REST_QUARTZ_TEST-Job",quantile="0.5"} 1.66921282E12
application_quartz_job_next_fire_time{configKey="REST_QUARTZ_TEST-Job",quantile="0.5"} 1.66921283E12
application_quartz_job_run_time{configKey="REST_QUARTZ_TEST-Job",quantile="0.5"} 41.0

----

==== Health - startup/liveness/readiness

A service támogatja a k8s probe-ok használatát.

* started
http://localhost:9000/q/health/started
* live
http://localhost:9000/q/health/live
* ready
http://localhost:9000/q/health/ready