= ticker 1.5.0 [[ticker_1_5_0]]

== Changes
* uber-jar -> fast-jar
* JSON logging enhancements - new configuration keys (detailed description: <<quarkus_config, Quarkus based configs>>):
** TICKER_JSON_MODULE_VERSION (Set in dockerfile. It is preferred for projects implementing ticker-core-quartz and building their own image to set it as well.)
** TICKER_JSON_MODULE_ID (Set in dockerfile. It is preferred for projects implementing ticker-core-quartz and building their own image to set it as well.)
** TICKER_JSON_K8S_NAMESPACE
** TICKER_JSON_MDC_FIELDS
** TICKER_JSON_EXCEPTION_OUTPUT_TYPE
** TICKER_JSON_DATE_FORMAT
* GELF logging: moduleId and moduleVersion values set in dockerfile. (It is preferred for projects implementing ticker-core-quartz and building their own image to set it as well.)
* `quarkus.log.console.enable` configuration mapped to TICKER_LOG_CONSOLE_ENABLE environment variable (default true)
* README translated to english

==== Migration

The changes are backward compatible and do not require migration.

