name: manual-RELEASE

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      comment:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Comment for release'
        # Default value if no value is explicitly provided
        default: 'Start release from WEB UI'
        # Input has to be provided for the workflow to run
        required: true
jobs:

  mvn-release:
    runs-on: ubuntu-latest
    # run only on main
    if: (github.ref_name == 'main' && contains('["rombow","czenczl","speter555"]', github.actor))

    steps:
      - name: Release
        uses: speter555/gh-action-mvn-release-main@v0.28.0
        with:
          GITHUB_TOKEN: '${{ secrets.GH_TOKEN_TECHUSER_JAVA }}'
          ARTIFACT_STORE_SERVER_ID: 'ossrh'
          SETTINGS_XML_PATH: '.github/.m2/settings.xml'
          GPG_KEY_ID_GITHUB_TECHUSER: '${{ secrets.GPG_KEY_ID_GITHUB_TECHUSER }}'
          GPG_SIGNING_KEY_GITHUB_TECHUSER: '${{ secrets.GPG_SIGNING_KEY_GITHUB_TECHUSER }}'
          SSH_PRIVATE_KEY_GITHUB_TECHUSER: '${{ secrets.SSH_PRIVATE_KEY_GITHUB_TECHUSER }}'
          TECH_USER_USERNAME: 'icellmobilsoft-robot'
          TECH_USER_PASSWORD: '${{ secrets.OSS_SONATYPE_ORG_PASSWORD }}'
          TECH_USER_EMAIL: 'github_techuser@icellmobilsoft.hu'
          JAVA_VERSION: '17'
          JAVA_DISTRIBUTION: 'temurin'
